name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: zer-far
          config_timezone: London/Europe
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_languages: no
          plugin_achievements: no
          plugin_achievements_threshold: B
